service_name: user_service
http_server:
  address: "localhost:3000"
database:
  connection_string: root:root@tcp(localhost:3306)/snuserservice?charset=utf8mb4&parseTime=True&loc=Local
  db_type: mysql
  migration_file_path: migrations