service-name: user_service
http-server:
  address: "localhost:3000"
database:
  connection-string: root:root@tcp(localhost:3306)/snuserservice?charset=utf8mb4&parseTime=True&loc=Local
  db-type: mysql
  migration-file-path: migrations
redis:
  address: "localhost:6379"
  password: ""
  db: 0
  pool-size: 1000
